"""adjusting exam table

Revision ID: 05f47a4c07d2
Revises: f72c7a7adffd
Create Date: 2025-12-19 20:38:59.768553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f47a4c07d2'
down_revision = 'f72c7a7adffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
