"""added grade

Revision ID: f72c7a7adffd
Revises: ad5645e1537b
Create Date: 2025-12-19 15:29:17.573473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72c7a7adffd'
down_revision = 'ad5645e1537b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_grade', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.drop_column('total_grade')

    # ### end Alembic commands ###
