"""Added Document model with AI text storage

Revision ID: fb3d67805c7e
Revises: b86fb7c99038
Create Date: 2025-12-14 16:45:03.874311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3d67805c7e'
down_revision = 'b86fb7c99038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
